workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.pointsredeemapp"
        NODE_OPTIONS: "--max_old_space_size=4096"
      node: 18.17.0
      java: 17
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Prebuild with Expo  
        script: |
          npx expo prebuild --platform android --clean
      - name: Set up local.properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build optimized APK (ARM64 only) and AAB
        script: |
          cd android
          chmod +x gradlew
          # Build ARM64 APK (most common, ~30-40 MB)
          ./gradlew assembleRelease -Dreact.native.architecture=arm64-v8a
          # Build App Bundle for Play Store (~50 MB, Google optimizes to 20-30 MB per device)
          ./gradlew bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - ahmedanwarabdulaziz@gmail.com
        notify:
          success: true
          failure: true
